# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

fail_fast: false
exclude: |
  (?x)(
    ^(.vscode/.*) |
    ^(bestsub/.*)
  )
files: '' # set '' as default

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=4096]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # Check RST
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  # Strong lint from ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args:
          - --fix
          - --show-fixes
      - id: ruff-format

  # Check yaml
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-yaml
        args:
          - --autofix
          - --offset=2
        exclude: |
          (?x)(
            ^(results/.*)
          )

  # Changes tabs to spaces
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs

  # Check jsonschema
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-readthedocs

  # Check for spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - >
            -L=lang
            ,TE
            ,Characts
            ,smoot
            ,nowe
            ,ameba
            ,avod
            ,cna
            ,doubleclick
            ,alog
            ,statics
            ,datas
            ,wew
            ,checbox
            ,rime
            ,splitted
          - --check-filenames
          - --write-changes
        exclude: |
          (?x)(
            ^(results/.*) |
            ^(templates/.*)
          )

  # Check for common shell mistakes
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
