name: Fetch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/3 * * *' # https://crontab.guru/#0_0/3_*_*_*
  push:
    paths:
      - 'sources.list'
      - 'config.yml'
      - 'abpwhite.txt'
      - '.github/workflows/**'
      - '**.py'
      - 'snippets/_*'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Insall requirements
        run: pip install -r requirements.txt
        
      - name: Fetch
        run: python ./fetch.py

      - name: Gernate commit date message
        id: commit-date-msg
        run: |
          echo "msg=$(date '+%Y-%m-%d %H:%M:%S') update" >> $GITHUB_OUTPUT

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
          file_pattern: 'snippets/* list*'
          commit_message: ${{ steps.commit-date-msg.outputs.msg }}
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          skip_fetch: true

      - name: Checkout ftw repo
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: actions/checkout@v4
        with:
          repository: msclock/ftw
          ref: master
          token: ${{ secrets.PAT }}
          path: msclock/ftw

      - name: Copy list files to ftw repo
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: cp list.yml list.meta.yml msclock/ftw/

      - name: Commit changes to ftw repo
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: msclock/ftw
          branch: master
          commit_message: ${{ steps.commit-date-msg.outputs.msg }}
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          push_options: --force
          skip_fetch: true
