name: x10hosting

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 */7 * *

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3
  TZ: Asia/Shanghai

jobs:
  update:
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run x10hosting
        env:
          X10HOSTING_COOKIES: ${{ secrets.X10HOSTING_COOKIES }}
        run: |
          python x10hosting.py
